services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=127.0.0.1
      - PORT=3000
      - SESSION_SECRET=SessionCat
      - TIMEOUT=3600000
      - DATABASE_URL=postgres://postgres:123@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d  # Mount the SQL script

volumes:
  pgdata: